### PR TITLE
Fix #128: CSRF whitelist or blacklist multiple endpoints.

### LINKED ISSUE #128: CSRF blacklist and whitelist not working as expected for multiple endpoints.
I am currently working with a package that uses `lusca` for CSRF protection and discovered that blacklisting and whitelisting does not work as expected when I pass an array of more than 1 endpoints. However, if a `string` or an `array` with just 1 endpoint is passed, it works as expected.

Here is a simple scenario from my app:

**This works as expected**

```js
expressApp.use(lusca.csrf({
  blacklist: ['/hooks/user_created']
}));
```

**This doesn't work as expected**

```js
expressApp.use(lusca.csrf({
  blacklist: [
    '/hooks/user_created',
    '/hooks/user_profile_updated',
    '/hooks/email_delivered'
  ]
}));
```

### PR DESCRIPTION
**Pull request by gladchinda**

### CODE REVIEW

**Comment by linkRace** [comment]
Same as #121 , merging that one

**Comment by polunzh** [comment]
I think this is better than #121 .

**Comment by gladchinda** [comment]
So, should I create a new pull request?

**Comment by gladchinda** [comment]
I noticed this issue has not been fixed yet. I am creating a new pull request for this.

**Pull request closed without merging**
