### PR TITLE
travis to build on latest node

### PR DESCRIPTION
**Pull request by suryagh**
I tested on my fork, and this updated builds are passing on Travis.

### CODE REVIEW

**Comment by shaunwarman** [comment]
👍

**Comment by grawk** [comment]
I feel like we still need a foot in the 0.x world... I know at least some people are in production with lusca and v0.10.

**Comment by jasisk** [comment]
> I feel like we still need a foot in the 0.x world

https://github.com/krakenjs/lusca/pull/87/files#diff-354f30a63fb0907d4ad57269548329e3R8

`¯\_(ツ)_/¯`

**Comment by indutny** [comment]
👍

**Pull request merged**
