### PR TITLE
Change whitelist/blacklist to allowlist/blocklist

### PR DESCRIPTION
**Pull request by linkRace**

### CODE REVIEW

**Comment by linkRace** [comment]
@grawk travis seems to be failing on old node versions for this, do you know who owns the config for those?

**Comment by grawk** [comment]
Hi @linkRace thanks for initiating this change.

Would you mind making a change to .travis.yml to select only node@10 and node@12 runtimes? The tests should pass with that change and we can move forward.

**Comment by linkRace** [comment]
Looks good now 👍

**Comment by linkRace** [comment]
Will merge this and submit another change before publishing as 1.7.0

**Pull request merged**
