### PR TITLE
Use lower case header can improve 3x performance

### PR DESCRIPTION
**Pull request by fengmk2**
see https://gist.github.com/fengmk2/1634043ec1d40e09b53197b817411131

### CODE REVIEW

**Comment by linkRace** [comment]
Hey @fengmk2 sorry for the delay, trying to take over maintaining this.  I'm assuming tests passed and whatnot?  Seems like a simple change otherwise, will want another +1 from my team.

**Comment by grawk** [comment]
LGTM. :+1:

**Comment by linkRace** [comment]
@indutny @shaunwarman @gabrielcsapo another +1 before merge?

**Comment by shaunwarman** [comment]
👍

**Comment by gabrielcsapo** [comment]
👍

**Comment by grawk** [comment]
👍

**Pull request merged**
